SERVICES:

  measurement:
    PORT: 50001
    DEPENDENCIES: []
    SERVICE_TYPE: Interface  # 'Interface' or 'Dashboard'
    SERVICE:
      DOWNLOAD_DATA: True
      INIT_DB: True
      DATADRIVE: /root/datadrive
      TABLE_DATA_SYSTEM: 'postgres'  # 'file' or 'postgres'
      TIME_SERIES_DATA_SYSTEM: 'influx'  # 'file' or 'influx'
      PREPROCESS:
        - 
          NAME: test_model
          TASK: structural_modeling
          METHOD: create_finite_element_model
          CFG:
            GEOMETRY_TYPE: PLATE
            WIDTH: 80
            HEIGHT: 10
            THICKNESS: 1
            WIDTH_DIVIDE_NUM: 8
            HEIGHT_DIVIDE_NUM: 1
            YOUNGS_MODULUS: 70e+3
            POISSONS_RATIO: 0.3
            R3: 0
            ELEM_TYPE: iQS4
            NODE_NUM: 4
            CONSTRAINT:  # constraint_dof: {node_id: constraint_value}
              123456:
                1: 0
                12: 0
        -
          NAME: test_sensor
          TASK: sensor_modeling
          METHOD: create_sensor
          CFG:
            SETTING_TYPE: discrete  # discrete, continuous
            LOCATIONAL: True
            DIRECTIONAL: False
            LOCATION: [
              [5, 5, 0], 
              [25, 5, 0],
              [45, 5, 0],
              [65, 5, 0],
              ]
        -
          NAME: test_sensor
          TASK: sensor_modeling
          METHOD: create_sensor_structural_model_connection
          CFG:
            COMPONENT_NAME: fe_node
            R1: 0
            R2: 0
            R3: -1
          STRUCTURAL_MODEL_NAME: test_model

      DATA_PROCESSING_METHOD: simulate_stream  # 'batch', 'stream', or 'simulate_stream'
      STREAM_EXPORT_QUEUE_MAXSIZE: 1000
      SIMULATE_STREAM_PARAMS:
        SLEEP_TIME: 1  # sec
        LOOP: True  # bool
        FIRST_TIMESTAMP: 1587772800  # sec
        LAST_TIMESTAMP: 1587772801  # sec
        INTERVAL: 1  # sec
    SUBPACKAGES:
      -
        TASK: measurement
        SUBPACKAGE_NAME: isas_subpackage_template.measurement
        MODEL_NAME: MeasurementTemplate
        INIT_ARGS:
          INSTANCE_NAME: measurement_template
          INPUT_DATA_NAMES: [ground_truth_rosette_strain_x]
          OUTPUT_DATA_NAMES: [simulated_rosette_strain_x]
          SENSOR_NAME: test_sensor
          SIMULATION: True
        PARAMS:
          TEST_KEY_1:
            TEST_KEY_1_2: 1.2
    EXPORT_DATA_NAMES: [simulated_rosette_strain_x]

  analysis:
    PORT: 50002
    DEPENDENCIES:
      - measurement
    SERVICE_TYPE: Interface  # 'Interface' or 'Dashboard'
    SERVICE:
      DOWNLOAD_DATA: False
      INIT_DB: False
      DATADRIVE: /root/datadrive
      TABLE_DATA_SYSTEM: 'postgres'  # 'file' or 'postgres'
      TIME_SERIES_DATA_SYSTEM: 'influx'  # 'file' or 'influx'
      PREPROCESS: []
      DATA_PROCESSING_METHOD: stream  # 'batch', 'stream', or 'simulate_stream'
      STREAM_EXPORT_QUEUE_MAXSIZE: 1000
    SUBPACKAGES:
      -
        TASK: analysis
        SUBPACKAGE_NAME: isas_subpackage_template.analysis
        MODEL_NAME: AnalysisTemplate
        INIT_ARGS:
          INSTANCE_NAME: analysis_template
          INPUT_DATA_NAME_DICT:
            input_quantity: [simulated_rosette_strain_x]
          OUTPUT_DATA_NAME_DICT:
            output_quantity: [analyzed_rosette_strain_x]
          STRUCTURAL_MODEL_NAME: test_model
        PARAMS:
          TEST_KEY_1:
            TEST_KEY_1_2: 1.2
    EXPORT_DATA_NAMES: [analyzed_rosette_strain_x]

  dashboard:
    PORT: 50003
    DEPENDENCIES:
      - measurement
      - analysis
    SERVICE_TYPE: Dashboard  # 'Interface' or 'Dashboard'
    SERVICE:
      DOWNLOAD_DATA: False
      INIT_DB: False
      DATADRIVE: /root/datadrive
      TABLE_DATA_SYSTEM: 'postgres'  # 'file' or 'postgres'
      TIME_SERIES_DATA_SYSTEM: 'influx'  # 'file' or 'influx'
      PREPROCESS: []
      DATA_PROCESSING_METHOD: stream  # 'batch', 'stream', or 'simulate_stream'
      LAYOUT:
        LAYOUT_NAME: src.content_layout
        COLOR_THEME: white
        PROJECT_TITLE: template_project
        WINDOW_TITLE: template_window
        WINDOW_WIDTH: 1280
        WINDOW_HEIGHT: 720
      INTERVAL: 100
    SUBPACKAGES:
      -
        TASK: visualization
        SUBPACKAGE_NAME: isas_subpackage_template.visualization
        MODEL_NAME: Dropdowns
        INIT_ARGS:
          INSTANCE_NAME: visualization_template_dropdowns
          SIZE_RATIO: [6, 6]
          INPUT_DATA_NAME_DICT:
          OUTPUT_DATA_NAME_DICT:
        PARAMS:
          DROPDOWN_LIST: ['a', 'b']
          VARIABLE_NAME: text
      -
        TASK: visualization
        SUBPACKAGE_NAME: isas_subpackage_template.visualization
        MODEL_NAME: TextDrawer
        INIT_ARGS:
          INSTANCE_NAME: visualization_template_textdrawer
          SIZE_RATIO: [6, 6]
          INPUT_DATA_NAME_DICT:
          OUTPUT_DATA_NAME_DICT:
        PARAMS:
          FONTSIZE: 20
          VARIABLE_NAME: text

NETWORK:
  NETWORK_NAME: project_network
  EXTERNAL: True
