PGPASSWORD=$POSTGRES_PASSWORD \
echo  "DROP DATABASE IF EXISTS $POSTGRES_DATABASE;
    CREATE DATABASE $POSTGRES_DATABASE;
    '\connect' $POSTGRES_DATABASE" \
    | xargs -I@ psql -U $POSTGRES_USER -c @
