SERVICE:
  DOWNLOAD_DATA: False
  INIT_DB: False
  DATADRIVE: /root/datadrive_tmp
  STATIC_DATA_SYSTEM: 'file'  # 'file' or 'postgres'
  DYNAMIC_DATA_SYSTEM: 'file'  # 'file' or 'influx'
  PREPROCESS: []
  DATA_PROCESSING_METHOD: batch  # 'batch', 'stream', or 'simulate_stream'
  STREAM_EXPORT_QUEUE_MAXSIZE: 100
  SIMULATE_STREAM_PARAMS:
    SLEEP_TIME: 1  # sec
    LOOP: False  # bool
    FIRST_TIMESTAMP: 1587772800  # sec
    LAST_TIMESTAMP: 1587772812  # sec
    INTERVAL: 1  # sec

SUBPACKAGES:
  -
    TASK: measurement
    SUBPACKAGE_NAME: isas_subpackage_template.measurement
    MODEL_NAME: MeasurementTemplate
    INIT_ARGS:
      INSTANCE_NAME: measurement_template
      INPUT_DATA_NAMES: [ground_truth_rosette_strain_x]
      OUTPUT_DATA_NAMES: [simulated_rosette_strain_x]
      SENSOR_NAME: 'test_sensor'
      SIMULATION: True
    PARAMS:
      TEST_KEY_1:
        TEST_KEY_1_2: 1.2
  -
    TASK: analysis
    SUBPACKAGE_NAME: isas_subpackage_template.analysis
    MODEL_NAME: AnalysisTemplate
    INIT_ARGS:
      INSTANCE_NAME: analysis_template
      INPUT_DATA_NAME_DICT:
        input_quantity: [simulated_rosette_strain_x]
      OUTPUT_DATA_NAME_DICT:
        output_quantity: [analyzed_rosette_strain_x]
      STRUCTURAL_MODEL_NAME: test_model
    PARAMS:
      TEST_KEY_1:
        TEST_KEY_1_2: 1.2

EXPORT_DATA_NAMES: [simulated_rosette_strain_x, analyzed_rosette_strain_x]
